# you need to specify a default configuration
# we probably only need one for these experiments

default:
  source.screen: "Broad"
  source.expression: !expr paste0("./data/processed/", source.screen, "/expression.csv")
  source.response: !expr paste0("./data/processed/", source.screen, "/responses.csv")
  gene.sets: !expr c('KEGG', 'LINCS')
  gene.sets.path: "./data/gene_subsets/"
  target.screen: "GDSC2"
  target.expression: !expr paste0("./data/processed/", target.screen, "/expression.csv")
  target.response: !expr paste0("./data/processed/", target.screen, "/responses.csv")
  models: !expr c('lasso','en','ridge')
  drugs: "./data/common_drugs.txt"
  experiment.type.is.positive: "false"
  results.dir: "./results/"
  results.features.dir: "features/"
  results.eval.dir: "evaluation/"
  results.correlations.dir: "correlations/"
  results.cv.dir: "cv/"
  results.metadata.dir: "metadata/"
  path.to.processed.screens: "./data/processed/"
  screens: !expr c('GDSC2', 'Broad', 'gCSI')
  target.screens: !expr c('GDSC2', 'gCSI')
  name.ccl.file: "ccl_data.csv"
  figs.dir: "./figs/"
  results.pagerank.features.dir: "pagerank_genes/"
  drugbank.data.file: "drugbank/AffectedGenesByDrug.txt"
  